### ISSUE TITLE
BUG Submit button on New patient form

### ISSUE THREAD

**Issue by taichan03** [CodeForPhilly/balancer-main#100]
BUG When users click submit on the New patient form, sometimes they have to click twice. We would like to fix it so that it will work with one click.

![Image](https://github.com/CodeForPhilly/balancer-main/assets/26842253/802e9710-9e44-40b7-b14a-3453d668db67)

**Comment by katjost** [comment]
Anyone can pick this up!

**Comment by snaeem3** [comment]
Hi,

I looked into this bug and it seems to be caused by the form not having a value set in the "Current State" field.

If you select an option, the form will submit on the first time. However if you skip it, maybe because 'Manic' is the correct option that you wanted, the form has the value saved as `null` and then it runs through this code in the `handleSubmit` function

```js
// Check if Diagnosis is "Null"
if (newPatientInfo.Diagnosis === "Null") {
   newPatientInfo.Diagnosis = "Manic";
   // setErrors(["Please select a current state."]);
   // window.scrollTo({ top: 0, behavior: "smooth" });
   return; // Prevent form submission
}
```

### Solution
I propose 2 options to solve this: 
1. Set _Manic_ or another option as the default, which may have been what the code was trying to do.
2. Require the user to set a _Current State_ and prevent form submission until an option is selected. See the screenshot below for an idea of what I'm suggesting 
![image](https://github.com/CodeForPhilly/balancer-main/assets/11710951/07b45571-9ed9-435c-8d63-d3d5fcdbec2a)

I'm not familiar enough with the application to say which route we should take. Both are fairly easy to implement so please let me know and I would be happy to help.

**Comment by katjost** [comment]
@snaeem3 you are awesome! Thank you for looking into this and proposing solutions. Let's go with Solution 1.
